name: Publish to NPM

on:
  push:
    branches:
    - master
    paths:
    - 'packages/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        always-auth: true
        node-version: 12.x
        registry-url: https://registry.npmjs.org
        scope: '@disruptph'
    - name: Install Dependencies
      run: yarn install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Build
      run: yarn run bootstrap
    - run: |
        git config user.name "Github Action"
        git config user.email "github-action@users.noreply.github.com"
    - name: Publish
      run: yarn run publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
